ALL_OUT_DIR: /ds3200_1/users_root/liuliangmin/workspace/PHD/run97/accurate_converge_files
CONTINUITY: 85
COVERAGE: 85
FILTERFRAGMENTS: 0.5
GENE_COUNT: 16000
GENOMES: /ds3200_1/users_root/liuliangmin/workspace/PHD/run97/input97
IDENTITY: 65
IDENTITY_DEEP: 40
LENGTH: 500
MASKSITES: 0.02
MAX_DUP: 10
NUM_INSTANCES: 6
OUT_DIR: /ds3200_1/users_root/liuliangmin/workspace/PHD/run97/accurate_output_97sp
REFERENCE: null
SCORES: HOXD55.q
STEPS: 1
SUPPORT_THRESHOLD: 0.95
UPPER_CASE: 0.9
